### ISSUE TITLE
build exited abnormally with code 125.

### ISSUE THREAD

**Issue by CDitzel** [ifitzpat/ob-docker-build#1]
I am trying to use your package for literal building of docker images from org mode. According to the README the following minimal example should suffice

#+begin_src docker-build :dir "."
FROM ubuntu:18.04
#+end_src

However, I am getting 

> docker build . -t  -f /tmp/babel-r2t9Zv/ob-docker-build-docker-ncny0G: exited abnormally with code 125.

would you be so kind and tell me if I am missing sth. here?

Also, it seems that the :dir argument is mandatory for some reason, why is that? and why does one need the quotes "" for that?

**Comment by ifitzpat** [comment]
Hi CDitzel,
Thanks for reporting this! It looks like this happens when the :tag parameter isn't specified. I'll see if I can provide a fix this weekend. In the meantime using :tag seems to be the workaround. The :dir parameter is mandatory because docker needs a build context. Rather than just assuming it's the default-directory I mandated it here (particularly because in some workflows orgfiles live in a separate directory from code). The quotes are optional unless the path contains spaces.

**Comment by CDitzel** [comment]
thanks for getting back to me on this one. I appreciate this package and the work you put into it!

**Comment by ifitzpat** [comment]
I pushed a fix for this issue. Please let me know if it works in your setup.

**Comment by CDitzel** [comment]
thanks for your effort, so going by 

```
#+begin_src docker-build :dir . :tag testimage:latest
FROM ubuntu:18.04
#+end_src
```
gives me 

> Wrong type argument: stringp, 0

whereas using quoation marks like 

```
#+begin_src docker-build :dir . :tag testimage:latest
FROM ubuntu:18.04
#+end_src
```

works. However what happens upon invocation via C-c C-c is that a new buffer *Org-babel Error Output* opens up with no content, while the actual interesting part, i.e. output of the docker build is shown in a concealed buffer in the background named 

/tmp/babel-fuc4fu/ob-docker-build-out-dnhxh 

that I need to pull up manually first in order to see whats going on. 

Emacs 26
Org Version 9.3.6

**Comment by ifitzpat** [comment]
>thanks for your effort, so going by
>#+begin_src docker-build :dir . :tag testimage:latest
>FROM ubuntu:18.04
>#+end_src
>gives me
>    Wrong type argument: stringp, 0

I can't seem to replicate this. Could you enable debug-on-error and send me the stack trace?

> However what happens upon invocation via C-c C-c is that a new buffer Org-babel Error Output opens up with no content,

This issue should be fixed in the latest commit.

**Comment by CDitzel** [comment]
the buffer issue seems to be resolved, I am using straight and so had to rebuild the package apparently. However, upon appearance of the buffer, there is a lot of content-flashing happening, until I see the message of successful build.

Referring to the :dir header-variable if quotation marks are left out, this is the trace

> Debugger entered--Lisp error: (wrong-type-argument stringp 0)
  expand-file-name(0)
  org-babel-execute-src-block(nil ("docker-build" "FROM ubuntu:18.04" ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:tag . "test:lat") (:dir . 0) (:push) (:context) (:tangle . "no") (:hlines . "no") (:noweb . "no") (:cache . "no") (:session . "none")) "" nil 1 "(ref:%s)"))
  org-ctrl-c-ctrl-c(nil)
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)
